<template>
  <div class="p-6 space-y-6">
    <!-- Header -->
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-2xl font-bold font-mono text-gray-200">System Reports</h1>
        <p class="text-gray-500 mt-1">Operational Reports and Analysis</p>
      </div>
      <div class="flex items-center space-x-4">
        <button class="btn-primary" @click="generateReport">
          <FileText class="w-4 h-4 mr-2" />
          Generate Report
        </button>
      </div>
    </div>

    <!-- Report Types -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <Card v-for="report in reportTypes" :key="report.id"
            :variant="report.status === 'ready' ? 'primary' : 'warning'"
            class="hover:border-primary/30 transition-colors cursor-pointer"
            @click="selectReport(report)">
        <div class="flex items-center justify-between mb-4">
          <h3 class="text-lg font-mono">{{ report.name }}</h3>
          <div class="flex items-center space-x-2">
            <span class="w-2 h-2 rounded-full"
                  :class="report.status === 'ready' ? 'bg-primary' : 'bg-secondary'"></span>
            <span class="text-xs font-mono"
                  :class="report.status === 'ready' ? 'text-primary' : 'text-secondary'">
              {{ report.status.toUpperCase() }}
            </span>
          </div>
        </div>
        <p class="text-sm text-gray-400 mb-4">{{ report.description }}</p>
        <div class="flex items-center justify-between text-xs text-gray-500">
          <span>Last Generated: {{ report.lastGenerated }}</span>
          <span>{{ report.frequency }}</span>
        </div>
      </Card>
    </div>

    <!-- Recent Reports -->
    <Card>
      <div class="flex items-center justify-between mb-4">
        <h2 class="text-lg font-mono">Recent Reports</h2>
        <div class="flex items-center space-x-2">
          <input type="text" 
                 v-model="search" 
                 placeholder="Search reports..."
                 class="px-3 py-1.5 bg-[#1a2233] text-gray-400 text-sm focus:outline-none">
          <select v-model="reportCategory"
                  class="px-3 py-1.5 bg-[#1a2233] text-gray-400 text-sm focus:outline-none">
            <option value="">All Categories</option>
            <option value="DAILY">Daily</option>
            <option value="WEEKLY">Weekly</option>
            <option value="MONTHLY">Monthly</option>
          </select>
        </div>
      </div>
      <div class="space-y-2">
        <div v-for="report in filteredReports" :key="report.id"
             class="p-4 bg-[#1a2233] hover:bg-[#243044] transition-colors">
          <div class="flex items-center justify-between mb-2">
            <div class="flex items-center space-x-4">
              <FileText class="w-5 h-5 text-gray-400" />
              <span class="font-mono text-gray-300">{{ report.name }}</span>
            </div>
            <div class="flex items-center space-x-4">
              <span class="text-xs text-gray-500">{{ report.date }}</span>
              <button class="p-2 bg-[#243044] hover:bg-[#2d3b55] text-gray-400"
                      @click="downloadReport(report)">
                <Download class="w-4 h-4" />
              </button>
            </div>
          </div>
          <div class="flex items-center space-x-4 text-xs text-gray-500">
            <span>Size: {{ report.size }}</span>
            <span>Type: {{ report.type }}</span>
            <span>Generated by: {{ report.author }}</span>
          </div>
        </div>
      </div>
    </Card>

    <!-- Report Generation Modal -->
    <div v-if="showModal" class="fixed inset-0 bg-black/50 flex items-center justify-center">
      <Card class="w-full max-w-2xl">
        <div class="flex items-center justify-between mb-6">
          <h2 class="text-xl font-mono">Generate Report</h2>
          <button class="text-gray-400 hover:text-gray-300"
                  @click="showModal = false">
            <X class="w-5 h-5" />
          </button>
        </div>
        <div class="space-y-4">
          <div>
            <label class="text-sm text-gray-400 block mb-2">Report Type</label>
            <select v-model="selectedReportType"
                    class="w-full px-4 py-2 bg-[#1a2233] text-gray-400 focus:outline-none">
              <option v-for="type in reportTypes" 
                      :key="type.id" 
                      :value="type.id">
                {{ type.name }}
              </option>
            </select>
          </div>
          <div>
            <label class="text-sm text-gray-400 block mb-2">Time Range</label>
            <div class="grid grid-cols-2 gap-4">
              <input type="date" 
                     v-model="dateRange.start"
                     class="px-4 py-2 bg-[#1a2233] text-gray-400 focus:outline-none">
              <input type="date" 
                     v-model="dateRange.end"
                     class="px-4 py-2 bg-[#1a2233] text-gray-400 focus:outline-none">
            </div>
          </div>
          <div>
            <label class="text-sm text-gray-400 block mb-2">Include Sections</label>
            <div class="space-y-2">
              <label v-for="section in reportSections" 
                     :key="section.id"
                     class="flex items-center space-x-2">
                <input type="checkbox" 
                       v-model="section.selected"
                       class="bg-[#1a2233]">
                <span class="text-sm text-gray-400">{{ section.name }}</span>
              </label>
            </div>
          </div>
          <div class="flex justify-end space-x-4 mt-6">
            <button class="btn-secondary" @click="showModal = false">Cancel</button>
            <button class="btn-primary" @click="generateSelectedReport">
              Generate
            </button>
          </div>
        </div>
      </Card>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { FileText, Download, X } from 'lucide-vue-next'
import Card from '@/components/ui/Card.vue'

const search = ref('')
const reportCategory = ref('')
const showModal = ref(false)
const selectedReportType = ref(null)
const dateRange = ref({ start: '', end: '' })

const reportTypes = ref([
  {
    id: 1,
    name: 'Daily Operations Report',
    description: 'Comprehensive daily operational statistics and events',
    status: 'ready',
    lastGenerated: '2024-03-15 08:00',
    frequency: 'Generated Daily'
  },
  {
    id: 2,
    name: 'Safety Systems Analysis',
    description: 'Detailed analysis of all safety systems and incidents',
    status: 'ready',
    lastGenerated: '2024-03-14 23:00',
    frequency: 'Generated Weekly'
  },
  {
    id: 3,
    name: 'Performance Metrics',
    description: 'System performance and efficiency metrics',
    status: 'processing',
    lastGenerated: '2024-03-14 12:00',
    frequency: 'Generated Daily'
  }
])

const recentReports = ref([
  {
    id: 1,
    name: 'Daily Operations Report - 2024-03-15',
    date: '2024-03-15 08:00',
    size: '2.4 MB',
    type: 'PDF',
    author: 'System',
    category: 'DAILY'
  },
  {
    id: 2,
    name: 'Weekly Safety Report - Week 11',
    date: '2024-03-14 23:00',
    size: '5.1 MB',
    type: 'PDF',
    author: 'Safety Officer',
    category: 'WEEKLY'
  },
  {
    id: 3,
    name: 'Monthly Performance Analysis - March',
    date: '2024-03-01 00:00',
    size: '8.7 MB',
    type: 'PDF',
    author: 'System',
    category: 'MONTHLY'
  }
])

const reportSections = ref([
  { id: 1, name: 'Operational Summary', selected: true },
  { id: 2, name: 'Safety Metrics', selected: true },
  { id: 3, name: 'Performance Analysis', selected: true },
  { id: 4, name: 'Event Log', selected: true },
  { id: 5, name: 'System Status', selected: true }
])

const filteredReports = computed(() => {
  return recentReports.value.filter(report => {
    const matchesSearch = report.name.toLowerCase().includes(search.value.toLowerCase())
    const matchesCategory = !reportCategory.value || report.category === reportCategory.value
    return matchesSearch && matchesCategory
  })
})

function selectReport(report) {
  selectedReportType.value = report.id
  showModal.value = true
}

function generateReport() {
  showModal.value = true
}

function generateSelectedReport() {
  // Implement report generation logic
  console.log('Generating report...', {
    type: selectedReportType.value,
    dateRange: dateRange.value,
    sections: reportSections.value.filter(s => s.selected)
  })
  showModal.value = false
}

function downloadReport(report) {
  console.log('Downloading report:', report.name)
}
</script>
